Pw fix okhttp dependency exception (#425)
* fixes missing depencency:
 Terminology server http://tx.fhir.orgException in thread "main" java.lang.NoClassDefFoundError: okhttp3/Request$Builder

* added optional tag to not break downstream projects (hapi)

* added dependency to cli as well